from django.db import models

# Create your models here.
class Player (models.Model):
	#Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
	name = models.CharField(("name"), max_length=100)
	position = models.CharField(("position"), max_length=25)
	age = models.IntegerField(("age"))
	team = models.CharField(("team"), max_length=100)
	gamesPlayed = models.IntegerField(("games played"))
	gamesStarted = models.IntegerField(("games started"))
	minutesPlayed = models.FloatField(("minutes played"))
	fg = models.FloatField(("field goals made"))
	fga = models.FloatField(("field goals attempted"))
	fgpercent = models.FloatField(("field goal percentage"))
	threepm = models.FloatField(("three pointers made"))
	threepa = models.FloatField(("three pointers attempted"))
	threeppercent = models.FloatField(("three point percentage"))
	twopm = models.FloatField(("two pointers made"))
	twopa = models.FloatField(("two pointers attempted"))
	twoppercent = models.FloatField(("two point percentage"))
	efg = models.FloatField(("effective field goal percentage"))
	ftm = models.FloatField(("free throws made"))
	fta = models.FloatField(("free throws attempted"))
	ftpercent = models.FloatField(("free throw percent"))
	oreb = models.FloatField(("offensive rebounds"))
	dreb = models.FloatField(("defensive rebounds"))
	reb = models.FloatField(("total rebounds"))
	ast = models.FloatField(("assists"))
	stl = models.FloatField(("steals"))
	blk = models.FloatField(("blocks"))
	tov = models.FloatField(("turnovers"))
	pf = models.FloatField(("personal fouls"))
	pts = models.FloatField(("points"))
	year = models.IntegerField(("year"))

	# age = models.CharField(max_length=100)
	# gamesPlayed = models.CharField(max_length=100)
	# gamesStarted = models.CharField(max_length=100)
	# minutesPlayed = models.CharField(max_length=100)
	# fg = models.CharField(max_length=100)
	# fga = models.CharField(max_length=100)
	# fgpercent = models.CharField(max_length=100)
	# threepm = models.CharField(max_length=100)
	# threepa = models.CharField(max_length=100)
	# threeppercent = models.CharField(max_length=100)
	# twopm = models.CharField(max_length=100)
	# twopa = models.CharField(max_length=100)
	# twoppercent = models.CharField(max_length=100)
	# efg = models.CharField(max_length=100)
	# ftm = models.CharField(max_length=100)
	# fta = models.CharField(max_length=100)
	# ftpercent = models.CharField(max_length=100)
	# oreb = models.CharField(max_length=100)
	# dreb = models.CharField(max_length=100)
	# reb = models.CharField(max_length=100)
	# ast = models.CharField(max_length=100)
	# stl = models.CharField(max_length=100)
	# blk = models.CharField(max_length=100)
	# tov = models.CharField(max_length=100)
	# pf = models.CharField(max_length=100)
	# pts = models.CharField(max_length=100)
	# year = models.CharField(max_length=100)


