# Generated by Django 4.2.2 on 2023-07-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('position', models.CharField(max_length=25, verbose_name='position')),
                ('age', models.IntegerField(verbose_name='age')),
                ('team', models.CharField(max_length=100, verbose_name='team')),
                ('gamesPlayed', models.IntegerField(verbose_name='games played')),
                ('gamesStarted', models.IntegerField(verbose_name='games started')),
                ('minutesPlayed', models.FloatField(verbose_name='minutes played')),
                ('fg', models.FloatField(verbose_name='field goals made')),
                ('fga', models.FloatField(verbose_name='field goals attempted')),
                ('fgpercent', models.FloatField(verbose_name='field goal percentage')),
                ('threepm', models.FloatField(verbose_name='three pointers made')),
                ('threepa', models.FloatField(verbose_name='three pointers attempted')),
                ('threeppercent', models.FloatField(verbose_name='three point percentage')),
                ('twopm', models.FloatField(verbose_name='two pointers made')),
                ('twopa', models.FloatField(verbose_name='two pointers attempted')),
                ('twoppercent', models.FloatField(verbose_name='two point percentage')),
                ('efg', models.FloatField(verbose_name='effective field goal percentage')),
                ('ftm', models.FloatField(verbose_name='free throws made')),
                ('fta', models.FloatField(verbose_name='free throws attempted')),
                ('ftpercent', models.FloatField(verbose_name='free throw percent')),
                ('oreb', models.FloatField(verbose_name='offensive rebounds')),
                ('dreb', models.FloatField(verbose_name='defensive rebounds')),
                ('reb', models.FloatField(verbose_name='total rebounds')),
                ('ast', models.FloatField(verbose_name='assists')),
                ('stl', models.FloatField(verbose_name='steals')),
                ('blk', models.FloatField(verbose_name='blocks')),
                ('tov', models.FloatField(verbose_name='turnovers')),
                ('pf', models.FloatField(verbose_name='personal fouls')),
                ('pts', models.FloatField(verbose_name='points')),
                ('year', models.IntegerField(verbose_name='year')),
            ],
        ),
    ]
